---
# playbook file for pre-yumrepos

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - set_fact:
      target_group_name: "{% if groups['new_nodes'] is defined and ( groups['new_nodes'] | length>0 ) %}new_nodes{% else %}nodes{% endif %}"
  - add_host:
      name: "{{ item }}"
      groups: target_group
    with_items: "{% if groups['new_nodes'] is defined and ( groups['new_nodes'] | length>0 ) %}{{ groups['new_nodes'] }}{% else %}{{ groups['nodes'] }}{% endif %}"
    changed_when: false
  - name: DEBUG:target_group name
    debug:
      msg: "{{ target_group_name }}"
  - name: DEBUG:target_group host
    debug:
      msg: "{{ groups['target_group'] }}"

- hosts: target_group
  connection: ssh
  gather_facts: no
  become: true
  pre_tasks:
  - name: Set repos_file_name
    set_fact:
      repos_file_name: ocp
    when: repos_file_name is not defined
  - name: Set repos_url_path
    set_fact:
      repos_url_path: http://192.168.122.1/repos/
    when: repos_url_path is not defined
  roles:
  - role: pre-yumrepos 
