---
# playbook file for pre-sysctl

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - set_fact:
      target_group_name: "{% if groups['new_nodes'] is defined and ( groups['new_nodes'] | length>0 ) %}new_nodes{% else %}nodes{% endif %}"
  - add_host:
      name: "{{ item }}"
      groups: target_group
    with_items: "{% if groups['new_nodes'] is defined and ( groups['new_nodes'] | length>0 ) %}{{ groups['new_nodes'] }}{% else %}{{ groups['nodes'] }}{% endif %}"
    changed_when: false
  - name: DEBUG:target_group name
    debug:
      msg: "{{ target_group_name }}"
  - name: DEBUG:target_group host
    debug:
      msg: "{{ groups['target_group'] }}"

- hosts: target_group
  connection: ssh
  gather_facts: no
  become: true
  pre_tasks:
  - name: Set sysctl_file_path
    set_fact:
      sysctl_file_path: /etc/sysctl.conf
    when: sysctl_file_path is not defined
  roles:
  - role: pre-sysctl 
